// <auto-generated />
using Census.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Census.API.Infrastructure.Migrations
{
    [DbContext(typeof(CensusDbContext))]
    [Migration("20190311122128_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Census.API.Model.ActualCensusEntity", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("State");

                    b.Property<double>("Households")
                        .HasColumnName("ActualHouseholds");

                    b.Property<double>("Population")
                        .HasColumnName("ActualPopulation");

                    b.HasKey("StateId");

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("Census.API.Model.EstimatedCensusEnity", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnName("State");

                    b.Property<int>("DistrictId")
                        .HasColumnName("Districts");

                    b.Property<double>("Households")
                        .HasColumnName("EstimatesHouseholds");

                    b.Property<double>("Population")
                        .HasColumnName("EstimatesPopulation");

                    b.HasKey("StateId", "DistrictId");

                    b.ToTable("Estimates");
                });
#pragma warning restore 612, 618
        }
    }
}
